namespace Simpllist.Delegates;

internal static class OutputDelegates
{
    
    public const string FileName = @"Simpllist.Wrapless.OutputDelegates.g.cs";
    public const string TypeName = "OutputDelegates";
    public const string TypeFullName = "Simpllist.Wrapless.OutputDelegates";
    public const string Value =
        @$"
// <auto-generated/>
#nullable enable
namespace Simpllist.Wrapless
{{
    public delegate void DigitalOutputSignal(string output, ushort value);
    public delegate void AnalogOutputSignal(string output, ushort value);
    public delegate void SerialOutputSignal(string output, string value);
}}
";
}