namespace Simpllist.Attributes;

internal static class InputAttribute
{
    public const string FileName = @"Simpllist.Wrapless.InputAttribute.g.cs";
    public const string TypeName = "Input";
    public const string TypeFullName = "Simpllist.Wrapless.InputAttribute";
    public const string Value =
        @$"
// <auto-generated/>
#nullable enable
namespace Simpllist.Wrapless
{{

    /// <summary>
    /// Adds an input as the annototed method to you SIMPL module
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    public sealed class InputAttribute : global::System.Attribute
    {{

    }}
}}
";
}