namespace Simpllist.Attributes;

internal static class ModuleAttribute
{
    public const string FileName = @"Simpllist.Wrapless.ModuleAttribute.g.cs";
    public const string TypeName = "Module";
    public const string TypeFullName = "Simpllist.Wrapless.ModuleAttribute";
    public const string Value =
        @$"
// <auto-generated/>
#nullable enable
namespace Simpllist.Wrapless
{{   
    /// <summary>
    /// Marks the class definition as a SIMPL + module
    /// Must be applied to a partial class definition.
    /// When applied the source generator will create metadata annotions used to create a SIMPL+ wrapper.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    public sealed class ModuleAttribute : global::System.Attribute
    {{
        /// <summary>
        /// The name of the Simpl+ module generated by the Simpllist Compiler
        /// </summary>
        public string ModuleName {{{{ get; set; }}}}

        ModuleAttribute(string moduleName)
        {{
            ModuleName = moduleName;
        }}
    }}
}}
";
}