namespace Simpllist.Interfaces;

internal static class LibraryInformationInterface
{
    public const string FileName = @"Simpllist.Wrapless.ILibraryInformation.g.cs";
    public const string TypeName = "ILibraryInformation";
    public const string TypeFullName = "Simpllist.Wrapless.ILibraryInformation";
    public const string Value =
        @$"
// <auto-generated/>
#nullable enable
namespace Simpllist.Wrapless
{{

    /// <summary>
    /// Provides read only properties containing the modules information for the module compiler
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    public interface {TypeName}
    {{
        string LibraryName {{ get; }}
        string DealerName {{ get; }}
        string SystemName {{ get; }}
        string Programmer {{ get; }}
        string Comments {{ get; }}
        string PdfHelpFile {{ get; }}

        global::System.Text.StringBuilder CommentsBuilder {{ get; }}
        global::System.Text.StringBuilder HelpBuilder {{ get; }}
        global::System.Text.StringBuilder IncludeBuilder {{ get; }}
    }}
}}
";
}