namespace Simpllist.Interfaces;

internal static class ModuleInformationInterface
{
    public const string FileName = @"Simpllist.Wrapless.ISimplPlusModuleInformation.g.cs";
    public const string TypeName = "ISimplPlusModuleInformation";
    public const string TypeFullName = "Simpllist.Wrapless.ISimplPlusModuleInformation";
    public const string Value =
        @$"
// <auto-generated/>
#nullable enable
namespace Simpllist.Wrapless
{{

    /// <summary>
    /// Provides read only properties containing the modules information for the module compiler
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    public interface {TypeName}
    {{
        string ModuleName {{ get; }}
        string DealerName {{ get; }}
        string SystemName {{ get; }}
        string Programmer {{ get; }}
        string Comments {{ get; }}
        string PdfHelpFile {{ get; }}

        global::System.Text.StringBuilder Builder {{ get; }}
    }}
}}
";
}