namespace Simpllist.Interfaces;

internal static class ModuleInterface
{
    public const string FileName = @"Simpllist.Wrapless.ISimplPlusModule.g.cs";
    public const string TypeName = "ISimplPlusModule";
    public const string TypeFullName = "Simpllist.Wrapless.ISimplPlusModule";
    public const string Value =
        @$"
// <auto-generated/>
#nullable enable
namespace Simpllist.Wrapless
{{

    /// <summary>
    /// Provides read only properties containing the modules information for the module compiler
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    public interface {TypeName}
    {{
        string ModuleName {{ get; }}
        string DealerName {{ get; }}
    }}
}}
";
}